### ISSUE TITLE
MOVE command

### ISSUE THREAD

**Issue by Cybranrules** [anneheijink/spectrangle-protocol#1]
It was decided the move-command to be overloaded, the example does have it implemented in the correct way;

the command should be: MOVE [tile] [location]
so:
 - when you play a tile you send for example: MOVE RGB0 5
 - when you swap you send: MOVE RGB0
 - when you skip you send: MOVE

**Comment by anneheijink** [comment]
To my understanding, that's not true. It was decided that a PLAY, SWAP, or SKIP keyword should be added to the command. Now, we can implement this in two different ways (with or without underscore):
- MOVE PLAY RGB0 5
- MOVE_PLAY RGB0 5

I went for the option with underscore, because I think this may be slightly easier to implement. (You can use the first element of String.Split(" ") as the command.

**Comment by Cybranrules** [comment]
we had decided the command MOVE was to be overloaded, this is easier to implement as you only need to check for the command move, and then send the arguments to a function which you overload.

i am quite (100%) sure we decided that it was to be overloaded

**Comment by anneheijink** [comment]
We decided to not overload that command, ie. add the PLAY, SWAP and SKIP keywords. I've checked this with several people. This was because several people didn't fully understand the command overloading.

Based on this, I've decided to use MOVE_PLAY, MOVE_SWAP and MOVE_SKIP.

For now I'm going to leave it this way. If you have any further questions, feel free to comment or ask me at the project session tomorrow afternoon.

As a side note, overloading is not necessarily easier to implement. Because this command is sent to the server only, the server has to send an UPDATE command anyway. When parsing the command, you have to distinguish between play, swap and skip anyway. In one case, you make the distinction by using separate commands. In the other case, you have to make the decision later on.
